package token

var TokenMap map[TokenType]string = map[TokenType]string{
	0:  "ILLEGAL",
	1:  "LPAREN",
	2:  "RPAREN",
	3:  "LBRACK",
	4:  "RBRACK",
	5:  "LBRACE",
	6:  "RBRACE",
	7:  "COMMA",
	8:  "SEMCOL",
	9:  "ASTER",
	10: "ASSIGN",
	11: "PREPROC",
	12: "DOT",
	14: "TILDE",
	15: "ARROW",
	16: "INCR",
	17: "DECR",
	18: "PLUS",
	19: "MINUS",
	20: "NOT",
	21: "SLASH",
	22: "PERCENT",
	23: "LSHIFT",
	24: "RSHIFT",
	25: "LT",
	26: "LE",
	27: "GT",
	28: "GE",
	29: "EQ",
	30: "NE",
	31: "AMP",
	32: "XOR",
	33: "PIPE",
	34: "AND",
	35: "OR",
	36: "QUESTION",
	37: "COLON",
	38: "PLUSEQ",
	39: "MINUSEQ",
	40: "ASTEREQ",
	41: "SLASHEQ",
	42: "PERCENTEQ",
	43: "AMPEQ",
	44: "XOREQ",
	45: "PIPEEQ",
	46: "LSHIFTEQ",
	47: "RSHIFTEQ",
	48: "SIZEOF",
}

var PunctuatorMap map[byte]TokenType = map[byte]TokenType{
	'(': LPAREN,
	')': RPAREN,
	'[': LBRACK,
	']': RBRACK,
	'{': LBRACE,
	'}': RBRACE,
	',': COMMA,
	';': SEMCOL,
	'*': ASTER,
	'=': ASSIGN,
	'#': PREPROC,
	'.': DOT,
	'~': TILDE,
}

var OperatorMap map[string]TokenType = map[string]TokenType{
	"->":  ARROW,
	"++":  INCR,
	"--":  DECR,
	"+":   PLUS,
	"-":   MINUS,
	"!":   NOT,
	"/":   SLASH,
	"%":   PERCENT,
	"<<":  LSHIFT,
	">>":  RSHIFT,
	"<":   LT,
	"<=":  LE,
	">":   GT,
	">=":  GE,
	"==":  EQ,
	"!=":  NE,
	"&":   AMP,
	"^":   XOR,
	"|":   PIPE,
	"&&":  AND,
	"||":  OR,
	"?":   QUESTION,
	":":   COLON,
	"+=":  PLUSEQ,
	"-=":  MINUSEQ,
	"*=":  ASTEREQ,
	"/=":  SLASHEQ,
	"%=":  PERCENTEQ,
	"&=":  AMPEQ,
	"^=":  XOREQ,
	"|=":  PIPEEQ,
	"<<=": LSHIFTEQ,
	">>=": RSHIFTEQ,
}

var OpSymbols []byte = []byte{
	'+', '-', '*', '/', '%', '&', '|', '^', '~', '!', '=', '<', '>', '?', ':',
}
